with open("WhatIf.user.js", "r+") as f:
    lines = f.read().splitlines()
    index = lines.index("// ==/UserScript==")
    lines[index + 1:index + 1] = [
        "\n", 
        "// THIS FILE IS AUTOGENERATED", 
        "// DO NOT MODIFY DIRECTLY",
        "\n"
    ]
    f.seek(0)
    f.write("\n".join(lines))